package com.codepad.foodai.domain.models

enum class ErrorCode(val code: String) {
    VALIDATION_ERROR("VALIDATION_ERROR"),
    INVALID_USER_ID("INVALID_USER_ID"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    DAILY_LIMIT_REACHED("DAILY_LIMIT_REACHED"),
    DUPLICATE_USER("DUPLICATE_USER"),
    TRANSCRIPT_NOT_AVAILABLE("TRANSCRIPT_NOT_AVAILABLE"),
    FOLDER_NOT_FOUND("FOLDER_NOT_FOUND"),
    DUPLICATE_ENTRY("DUPLICATE_ENTRY"),
    NOT_FOUND("NOT_FOUND"),
    INVALID_FIELD_NAME("INVALID_FIELD_NAME"),
    INVALID_FIELD_VALUE("INVALID_FIELD_VALUE"),
    NO_FILE_UPLOADED("NO_FILE_UPLOADED"),
    PARSING_ERROR("PARSING_ERROR"),
    TRANSCRIPTION_ERROR("TRANSCRIPTION_ERROR"),
    SUMMARIZATION_ERROR("SUMMARIZATION_ERROR"),
    INVALID_OPERATION("INVALID_OPERATION"),
    INVALID_FOLDER_ID("INVALID_FOLDER_ID"),
    PROCESSING_ERROR("PROCESSING_ERROR"),
    FILE_READ_ERROR("FILE_READ_ERROR"),
    INVALID_IMAGE_ID("INVALID_IMAGE_ID"),
    IMAGE_NOT_FOUND("IMAGE_NOT_FOUND"),
    INVALID_EXERCISE_ID("INVALID_EXERCISE_ID"),
    EXERCISE_NOT_FOUND("EXERCISE_NOT_FOUND"),
    PREMIUM_REQUIRED("PREMIUM_REQUIRED"),
    INVALID_MEAL_TYPE("INVALID_MEAL_TYPE"),
    INVALID_RECIPE_ID("INVALID_RECIPE_ID"),
    RECIPE_NOT_FOUND("RECIPE_NOT_FOUND"),

    // Community specific error codes
    COMMUNITY_POST_NOT_FOUND("COMMUNITY_POST_NOT_FOUND"),
    COMMUNITY_IMAGE_NOT_FOUND("COMMUNITY_IMAGE_NOT_FOUND"),
    COMMUNITY_USER_NOT_FOUND("COMMUNITY_USER_NOT_FOUND"),
    COMMUNITY_USER_NAME_NOT_SET("COMMUNITY_USER_NAME_NOT_SET"),
    COMMUNITY_ALREADY_POSTED("COMMUNITY_ALREADY_POSTED"),
    COMMUNITY_INVALID_OPERATION("COMMUNITY_INVALID_OPERATION"),
    COMMUNITY_COMMENT_NOT_FOUND("COMMUNITY_COMMENT_NOT_FOUND"),
    COMMUNITY_UNAUTHORIZED("COMMUNITY_UNAUTHORIZED"),
    COMMUNITY_INTERNAL_SERVER_ERROR("COMMUNITY_INTERNAL_SERVER_ERROR");

    override fun toString(): String = code
} 